insert into families_profesionals(nom) values
("Informatica"),
("Administratiu"),
("Automocio"),
("Manteniment i serveis de produccio"),
("Fabricacio mecanica"),
("Aigües");

insert into cicles(nom, familia_profesional) values
("Sistemes microinformatics i xarxes",1),
("Gestio administrativa",2),
("Electromecanica de vehicles automobils",3),
("Manteniment electromecanics",4),
("Mecanitzacio",5),

("Administracio de sistemes informatics en xarxa - orientat a Ciberseguretat",1),
("Desenvolupament daplicacions multiplataforma",1),
("Desenvolupament daplicacions web",1),
("Administracio i finances",2),
("Assistencia a la direccio",2),
("Automocio",3),
("Mecatronica industrial",4),
("Programacio de la produccio en fabricacio mecanica",5),
("Gestio de laigua",6);

INSERT INTO ocupacions(nom, cicle) 
VALUES ("Personal tecnic de suport informatic",1),
("Personal tecnic de xarxes de dades",1),
("Personal reparador de periferics de sistemes microinformatics",1),
("Comercials de microinformatica",1),
("Personal operador de teleassistencia",1),
("Personal operador de sistemes",1),
("Personal auxiliar administratiu",2),
("Personal ajudant doficina",2),
("Personal auxiliar administratiu de cobraments i pagaments",2),
("Personal administratiu comercial",2),
("Personal auxiliar administratiu de gestio de personal",2),
("Personal auxiliar administratiu de les administracions publiques",2),
("Recepcionista",2),
("Personal empleat datencio al client",2),
("Personal empleat de tresoreria",2),
("Personal empleat de mitjans de pagament",2),
("Electronicistes de vehicles", 3),
("Electricistes electronics de manteniment i reparacio en automocio", 3),
("Personal mecanic dautomobils", 3),
("Electricistes dautomobils", 3),
("Personal electromecanic dautomobils", 3),
("Personal mecanic de motors i els seus sistemes auxiliars dautomobils i motocicletes", 3),
("Personal reparador de sistemes pneumatics i hidraulics", 3),
("Personal reparador de sistemes de transmissio i de frens", 3),
("Personal reparador de sistemes de direccio i suspensio", 3),
("Personal operari dITV.", 3),
("Personal instal·lador daccessoris en vehicles.", 3),
("Personal operari dempreses dedicades a la fabricacio de recanvis.", 3),
("Personal electromecanic de motocicletes.", 3),
("Personal venedor/distribuïdor de recanvis i dequips de diagnosi.", 3),
("Mecanic de manteniment",4),
("Muntador industrial",4),
("Muntador dequips electrics",4),
("Muntador dequips electronics",4),
("Mantenidor de linia automatitzada",4),
("Muntador de bens dequip",4),
("Muntador dautomatismes pneumatics i hidraulics",4),
("Instal·lador electricista industrial",4),
("Electricista de manteniment i reparacio dequips de control, mesura i precisio",4),
("Personal ajustador operari de maquines eina", 5),
("Personal polidor de metalls i afilador deines", 5),
("Personal operador de maquines per treballar metalls", 5),
("Personal operador de maquines eina", 5),
("Personal operador de robots industrials", 5),
("Personal treballador de la fabricacio deines, mecanic i ajustador, modelista matricer i similars", 5),
("Personal torner, fresador i mandrinador", 5),
("Personal tecnic en administracio de sistemes", 6),
("Responsable dinformatica", 6),
("Personal tecnic en serveis dInternet", 6),
("Personal tecnic en serveis de missatgeria electronica", 6),
("Personal de recolzament i suport tecnic", 6),
("Personal tecnic en teleassistencia", 6),
("Personal tecnic en administracio de base de dades", 6),
("Personal tecnic de xarxes", 6),
("Personal supervisor de sistemes", 6),
("Personal tecnic en serveis de comunicacions", 6),
("Personal tecnic en entorns web", 6),
("Desenvolupar aplicacions informatiques per a la gestio empresarial i de negoci.", 7),
("Desenvolupar aplicacions de proposit general.", 7),
("Desenvolupar aplicacions en lambit de lentreteniment i la informatica mobil.", 7),
("Programador web", 8),
("Programador multimedia", 8),
("Desenvolupador daplicacions en entorns web", 8),("Administratiu doficina", 9),
("Administratiu comercial", 9),
("Administratiu financer", 9),
("Administratiu comptable", 9),
("Administratiu de logistica", 9),
("Administratiu de banca i dassegurances", 9),
("Administratiu de recursos humans", 9),
("Administratiu de lAdministracio publica", 9),
("Administratiu dassessories juridiques, comptables, laborals, fiscals o gestories", 9),
("Tecnic en gestio de cobraments", 9),
("Responsable datencio al client", 9),
("Assistent a la direccio", 10 ),
("Assistent personal", 10 ),
("Secretari de direccio", 10 ),
("Assistent de despatxos i oficines", 10 ),
("Assistent juridic", 10 ),
("Assistent en departaments de recursos humans", 10 ),
("Assistent en departaments de recursos humans", 10 ),
("Cap de larea delectromecanica", 11),
("Recepcionista de vehicles", 11),
("Cap de taller de vehicles de motor", 11),
("Personal encarregat dITV", 11),
("Personal perit taxador de vehicles", 11),
("Cap de servei", 11),
("Personal encarregat darea de recanvis", 11),
("Personal encarregat darea comercial dequips relacionats amb els vehicles", 11),
("Cap de larea de carrosseria: xapa i pintura", 11),
("Tecnic en planificacio i programacio de processos de manteniment dinstal·lacions de maquinaria i equip industrial.", 12),
("Cap dequip de muntadors dinstal·lacions de maquinaria i equip industrial.", 12),
("Cap dequip de mantenidors dinstal·lacions de maquinaria i equip industrial.", 12),
("Tecnic o tecnica en mecanica", 13),
("Encarregat o encarregada dinstal·lacions de processament de metalls", 13),
("Encarregat o encarregada doperadors de maquines per treballar metalls", 13),
("Encarregat o encarregada de muntadors", 13),
("Programador o programadora de CNC (control numeric amb ordinador)", 13),
("Programador o programadora de sistemes automatitzats en fabricacio mecanica", 13),
("Programador o programadora de la produccio", 13),
("Encargado de montaje de redes de abastecimiento y distribucion de agua.", 14),
("Encargado de montaje de redes e instalaciones de saneamiento.", 14),
("Encargado de mantenimiento de redes de agua.", 14),
("Encargado de mantenimiento de redes de saneamiento.", 14),
("Operador de planta de tratamiento de agua de abastecimiento.", 14),
("Operador de planta de tratamiento de aguas residuales.", 14),
("Tecnico en gestion del uso eficiente del agua.", 14),
("Tecnico en sistemas de distribucion de agua.", 14);



