insert into families_profesionals(nom) values
("Informàtica"),
("Administratiu"),
("Automoció"),
("Manteniment i serveis de producció"),
("Fabricació mecànica"),
("Aigües");

insert into cicles(nom, familia_profesional) values
("Sistemes microinformàtics i xarxes",1),
("Gestió administrativa",2),
("Electromecànica de vehicles automòbils",3),
("Manteniment electromecànics",4),
("Mecanització",5),

("Administració de sistemes informàtics en xarxa - orientat a Ciberseguretat",1),
("Desenvolupament d’aplicacions multiplataforma",1),
("Desenvolupament d’aplicacions web",1),
("Administració i finances",2),
("Assistència a la direcció",2),
("Automoció",3),
("Mecatrònica industrial",4),
("Programació de la producció en fabricació mecànica",5),
("Gestió de l’aigua",6);

INSERT INTO ocupacions(nom, cicle) 
VALUES ("Personal tècnic de suport informàtic",1),
("Personal tècnic de xarxes de dades",1),
("Personal reparador de perifèrics de sistemes microinformàtics",1),
("Comercials de microinformàtica",1),
("Personal operador de teleassistència",1),
("Personal operador de sistemes",1),
("Personal auxiliar administratiu",2),
("Personal ajudant d’oficina",2),
("Personal auxiliar administratiu de cobraments i pagaments",2),
("Personal administratiu comercial",2),
("Personal auxiliar administratiu de gestió de personal",2),
("Personal auxiliar administratiu de les administracions públiques",2),
("Recepcionista",2),
("Personal empleat d’atenció al client",2),
("Personal empleat de tresoreria",2),
("Personal empleat de mitjans de pagament",2),
("Electronicistes de vehicles", 3),
("Electricistes electrònics de manteniment i reparació en automoció", 3),
("Personal mecànic d’automòbils", 3),
("Electricistes d’automòbils", 3),
("Personal electromecànic d’automòbils", 3),
("Personal mecànic de motors i els seus sistemes auxiliars d’automòbils i motocicletes", 3),
("Personal reparador de sistemes pneumàtics i hidràulics", 3),
("Personal reparador de sistemes de transmissió i de frens", 3),
("Personal reparador de sistemes de direcció i suspensió", 3),
("Personal operari d'ITV.", 3),
("Personal instal·lador d’accessoris en vehicles.", 3),
("Personal operari d’empreses dedicades a la fabricació de recanvis.", 3),
("Personal electromecànic de motocicletes.", 3),
("Personal venedor/distribuïdor de recanvis i d’equips de diagnosi.", 3),
("Mecànic de manteniment",4),
("Muntador industrial",4),
("Muntador d'equips elèctrics",4),
("Muntador d'equips electrònics",4),
("Mantenidor de línia automatitzada",4),
("Muntador de béns d'equip",4),
("Muntador d'automatismes pneumàtics i hidràulics",4),
("Instal·lador electricista industrial",4),
("Electricista de manteniment i reparació d'equips de control, mesura i precisió",4),
('Personal ajustador operari de màquines eina', 5),
('Personal polidor de metalls i afilador d’eines', 5),
('Personal operador de màquines per treballar metalls', 5),
('Personal operador de màquines eina', 5),
('Personal operador de robots industrials', 5),
('Personal treballador de la fabricació d’eines, mecànic i ajustador, modelista matricer i similars', 5),
('Personal torner, fresador i mandrinador', 5),
('Personal tècnic en administració de sistemes', 6),
('Responsable d’informàtica', 6),
('Personal tècnic en serveis d’Internet', 6),
('Personal tècnic en serveis de missatgeria electrònica', 6),
('Personal de recolzament i suport tècnic', 6),
('Personal tècnic en teleassistència', 6),
('Personal tècnic en administració de base de dades', 6),
('Personal tècnic de xarxes', 6),
('Personal supervisor de sistemes', 6),
('Personal tècnic en serveis de comunicacions', 6),
('Personal tècnic en entorns web', 6),
('Desenvolupar aplicacions informàtiques per a la gestió empresarial i de negoci.', 7),
('Desenvolupar aplicacions de propòsit general.', 7),
('Desenvolupar aplicacions en l’àmbit de l’entreteniment i la informàtica mòbil.', 7),
('Programador web', 8),
('Programador multimèdia', 8),
('Desenvolupador d’aplicacions en entorns web', 8),('Administratiu d''oficina', 9),
('Administratiu comercial', 9),
('Administratiu financer', 9),
('Administratiu comptable', 9),
('Administratiu de logística', 9),
('Administratiu de banca i d''assegurances', 9),
('Administratiu de recursos humans', 9),
('Administratiu de l''Administració pública', 9),
('Administratiu d''assessories jurídiques, comptables, laborals, fiscals o gestories', 9),
('Tècnic en gestió de cobraments', 9),
('Responsable d''atenció al client', 9),
( 'Assistent a la direcció', 10 ),
( 'Assistent personal', 10 ),
( 'Secretari de direcció', 10 ),
( 'Assistent de despatxos i oficines', 10 ),
( 'Assistent jurídic', 10 ),
( 'Assistent en departaments de recursos humans', 10 ),
( 'Assistent en departaments de recursos humans', 10 ),
('Cap de l’àrea d’electromecànica', 11),
('Recepcionista de vehicles', 11),
('Cap de taller de vehicles de motor', 11),
('Personal encarregat d’ITV', 11),
('Personal perit taxador de vehicles', 11),
('Cap de servei', 11),
('Personal encarregat d’àrea de recanvis', 11),
('Personal encarregat d’àrea comercial d’equips relacionats amb els vehicles', 11),
('Cap de l’àrea de carrosseria: xapa i pintura', 11),
('Tècnic en planificació i programació de processos de manteniment d''instal·lacions de maquinària i equip industrial.', 12),
('Cap d''equip de muntadors d''instal·lacions de maquinària i equip industrial.', 12),
('Cap d''equip de mantenidors d''instal·lacions de maquinària i equip industrial.', 12),
('Tècnic o tècnica en mecànica', 13),
('Encarregat o encarregada d''instal·lacions de processament de metalls', 13),
('Encarregat o encarregada d''operadors de màquines per treballar metalls', 13),
('Encarregat o encarregada de muntadors', 13),
('Programador o programadora de CNC (control numèric amb ordinador)', 13),
('Programador o programadora de sistemes automatitzats en fabricació mecànica', 13),
('Programador o programadora de la producció', 13),
('Encargado de montaje de redes de abastecimiento y distribución de agua.', 14),
('Encargado de montaje de redes e instalaciones de saneamiento.', 14),
('Encargado de mantenimiento de redes de agua.', 14),
('Encargado de mantenimiento de redes de saneamiento.', 14),
('Operador de planta de tratamiento de agua de abastecimiento.', 14),
('Operador de planta de tratamiento de aguas residuales.', 14),
('Técnico en gestión del uso eficiente del agua.', 14),
('Técnico en sistemas de distribución de agua.', 14);



